print("숫자입력")
x = input()
print(float(x) , "inch")
print(float(x) * 2.54 , "cm")

str_input = input("숫자입력")
num_input = float(str_input)
print()
print(num_input , "inch")
print((num_input * 2.54),"cm")